from typing import List
from pyVmomi import vmodl
from datetime import datetime


class VibInfo(vmodl.DynamicData):
    @property
    def id(self) -> str: ...
    @property
    def name(self) -> str: ...
    @property
    def version(self) -> str: ...
    @property
    def vendor(self) -> str: ...
    @property
    def summary(self) -> str: ...
    @property
    def softwareTags(self) -> VibInfo.SoftwareTags: ...
    @property
    def releaseDate(self) -> datetime: ...


    class SoftwareTags(vmodl.DynamicData):
        @property
        def tags(self) -> List[str]: ...