from pyVmomi import vmodl
from pyVmomi.VmomiSupport import long


class DatastoreSpaceStatistics(vmodl.DynamicData):
    @property
    def profileId(self) -> str: ...
    @property
    def physicalTotalInMB(self) -> long: ...
    @property
    def physicalFreeInMB(self) -> long: ...
    @property
    def physicalUsedInMB(self) -> long: ...
    @property
    def logicalLimitInMB(self) -> long: ...
    @property
    def logicalFreeInMB(self) -> long: ...
    @property
    def logicalUsedInMB(self) -> long: ...